# Generated by Django 3.2.5 on 2021-07-23 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aktor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.PositiveIntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='aktor.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aktor.employee')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aktor.customer')),
                ('total_item', models.ManyToManyField(related_name='total_item', to='transactions.ItemOrder')),
            ],
        ),
    ]
